# action.yaml
name: 'Simple MS Teams Notifier Action'
description: 'A Github Action that sends notification to the MS Teams'
author: "Rafal Slowik"
branding:
  icon: "activity" # icon name from Feather open source icons pack
  color: "blue"

inputs:
  status:
    description: "Status of the job, allowed values: 'success', 'cancelled', 'failure'"
    required: true
    default: ${{ job.status }}
  job_name:
    description: 'Name of the job'
    required: false
    default: ${{ github.job }}
  workflow_name:
    description: 'Name of the workflow'
    required: true
    default: ${{ github.workflow }}
  triggering_actor:
    description: 'Who triggered the workflow'
    required: true
    default: ${{ github.triggering_actor }}
  facts:
    description: 'Additional facts'
    required: true
    default: '{"Reference":"${{ github.ref }}"}'
  repo_server_url:
    description: 'Repository server URL'
    required: true
    default: ${{ github.server_url }}
  repo_name:
    description: 'Repository name'
    required: true
    default: ${{github.repository}}
  github_sha:
    description: 'Github SHA'
    required: true
    default: ${{github.sha}}
  run_id:
    description: 'Workflow run ID '
    required: true
    default: ${{github.run_id}}
  token:
    description: 'GitHub token'
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  webhook_uri:
    description: 'MS Teams webhook URI'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Change directory and validate input
      run: |
          [[ "${{ inputs.status }}" ]] || { echo "status is not provided" ; exit 1; }
          [[ "${{ inputs.job_name }}" ]] || { echo "job_name is not provided" ; exit 1; }
          [[ "${{ inputs.workflow_name }}" ]] || { echo "workflow_name is not provided" ; exit 1; }
          [[ "${{ inputs.triggering_actor }}" ]] || { echo "triggering_actor is not provided" ; exit 1; }
          [[ "${{ inputs.facts }}" ]] || { echo "facts is not provided" ; exit 1; }
          [[ "${{ inputs.repo_server_url }}" ]] || { echo "repo_server_url is not provided" ; exit 1; }
          [[ "${{ inputs.repo_name }}" ]] || { echo "repo_name is not provided" ; exit 1; }
          [[ "${{ inputs.github_sha }}" ]] || { echo "github_sha is not provided" ; exit 1; }
          [[ "${{ inputs.run_id }}" ]] || { echo "  run_id is not provided" ; exit 1; }
          [[ "${{ inputs.webhook_uri }}" ]] || { echo "webhook_uri is not provided" ; exit 1; }
      shell: bash
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
        token: ${{ inputs.token }}
    - name: Sends a notification to ms teams
      id: send-msteams
      env:
        STATUS: ${{ inputs.status }}
        JOB_NAME: ${{ inputs.job_name }}
        WORKFLOW_NAME: ${{ inputs.workflow_name }}
        TRIGGERING_ACTOR: ${{ inputs.triggering_actor }}
        FACTS: ${{ inputs.facts }}
        REPO_SERVER_URL: ${{ inputs.repo_server_url }}
        REPO_NAME: ${{ inputs.repo_name }}
        GITHUB_SHA: ${{ inputs.github_sha }}
        RUN_ID: ${{ inputs.run_id }}
        WEBHOOK_URI: ${{ inputs.webhook_uri }}
      run: |
        cd ${{github.action_path}}
        pip install --upgrade pip
        pip install -r requirements.txt --use-pep517
        python3 src/main.py
      shell: bash
